version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bad-word-checker
    ports:
      - "8089:8089"
    volumes:
      - ./static:/app/static
      - ./assets:/app/assets
    environment:
      - ENV_VAR=value
    restart: unless-stopped
    healthcheck:
      test: ["curl", "-f", "http://localhost:8089/healthz"]
      interval: 15m
      timeout: 10s
      retries: 5
      start_period: 30s
      